### ISSUE TITLE
Not even starting

### ISSUE THREAD

**Issue by jourdanrodrigues** [GrafGenerator/gulp-json-server#20]
Yep, is that simple. :) Maybe some update in Lodash broke it.

The only output is this one:

```
[12:00:04] 'webservice' errored after 330 ms
[12:00:04] TypeError in plugin 'gulp-json-srv'
Message:
    lodash.runInContext is not a function
```

Some info about my environment:
- Node: v6.9.1
- Gulp: 3.9.1
- NPM: 3.10.8
- OS: Ubuntu 16.10

**Comment by GrafGenerator** [comment]
@jourdanrodrigues, did you tried to reinstall dependencies? This plugin do not use lodash.runInContext, it's used in lowdb, upon which json-server is built.
Try to run json-server manually, if it's erroring, then the issue should be with json-server itself, probably it's caused by the lodash update as you stated.

**Comment by jourdanrodrigues** [comment]
@GrafGenerator Sorry, I didn't update.

The _json-server_ package works fine here.

It is a problem with _gulp-json-server_. [This comment](https://github.com/typicode/json-server/issues/303#issuecomment-239788150) proposes a solution that worked for me, but I think it's too manual.

I downloaded _gulp-json-server_, installed the dependencies and added it to my project instead of npm's (manually installed it) and also worked fine.

**Comment by GrafGenerator** [comment]
@jourdanrodrigues So why you decided that issue is with `gulp-json-srv`?  The discussion in the issue that you've pointed clearly states that the issue appears when there's no appropriate lodash@4 version installed for project and lowdb accidentally gets the lower version. Gulp-json-srv currently uses lodash@4, so there is no problems here.
If the issue was with `gulp-json-srv` dependencies, then tests running on clear machine would show that. But they are not, as well as my check that I did on my PC now. I still think that the issue is with your dependencies configuration, and I do not understand what kind of fix do you expect, if adding lodash as dev(!) dependency is too manual. 
To fix the issue, at least stable reproduce steps needed.

**Comment by jourdanrodrigues** [comment]
@GrafGenerator I tested isolated with `json-server` only and worked fine. Don't know if the global scope changes anything.

I think adding `lodash` as a dependency of my project is too manual due to the fact that I don't actually use it.

You're probably right about the issue not being from `gulp-json-srv`. Closing it. :laughing: 

Thanks!
